// ─── Annotation Modes ───

export type AnnotationMode = 'overview' | 'depth';
export type ViewMode = 'overview' | 'depth' | 'all';

// ─── User Context (depth mode) ───

export type UserContextMode =
  | 'info-takeaway'
  | 'brainstorm'
  | 'argument-formation'
  | 'decision'
  | 'learning';

export type UserContext = {
  mode?: UserContextMode;
  note?: string;
};

// ─── Overview Labels ───

export type OverviewLabel =
  | 'core_claim'
  | 'evidence'
  | 'outcome'
  | 'background'
  | 'transition';

// ─── Depth Types ───

export type DepthType =
  | "insight"
  // Legacy values kept for backward compat with cached/stored annotations
  | "caveat"
  | "counterargument"
  | "alternative"
  | "fallacy"
  | "criteria"
  | "perspective"
  | "consequence"
  | "recall"
  | "translation"
  | "decision_making"
  | "juxtaposition"
  | "outsider"
  | "fixation_breaker"
  | "incomplete_move"
  | "personal_hook"
  | "role_assignment"
  | "exaggeration"
  | "reverse_brainstorm"
  | "study"
  | "vocabulary";

// ─── Unified Annotation Type ───

export type AnnotationType = OverviewLabel | DepthType | "user_written";

export type TextQuoteSelector = {
  type: "TextQuoteSelector";
  exact: string;
  prefix?: string;
  suffix?: string;
};

export type AnnotationContent = {
  note: string;
  why_it_matters?: string;
  question?: string;
  /** @deprecated No longer generated by LLM, kept for cached data backward compat */
  suggestions?: string[];
};

export type Verdict = "TAKE" | "CAUTION" | "THROW";

export type Annotation = {
  id: string;
  mode: AnnotationMode;
  type: AnnotationType;
  /** LLM-generated title (overview chunks). Falls back to ANNOTATION_LABELS[type] when absent. */
  label?: string;
  anchor: TextQuoteSelector;
  content: AnnotationContent;
  /** Chunk boundaries for overview mode — marks the start and end of the text chunk this annotation covers. */
  chunk?: {
    start: TextQuoteSelector;
    end: TextQuoteSelector;
  };
  /** Worldview lens key used for this annotation (depth mode only). */
  worldview?: string;
  /** Display name of the worldview thinker (e.g., "Richard Feynman"). */
  worldviewName?: string;
  /** Verdict assigned by the annotator: TAKE, CAUTION, or THROW. */
  verdict?: Verdict;
  /** Whether this claim was introduced by the AI rather than requested by the user. */
  aiIntroduced?: boolean;
};

export type AnnotationResponse = {
  success: boolean;
  cached: boolean;
  annotations: Annotation[];
  feedback?: AnnotationFeedback[];
};

// ─── Feedback ───

export type FeedbackType = "thumbs_up" | "thumbs_down" | "reply";

export type AnnotationFeedback = {
  id: string;
  annotation_id: string;
  feedback_type: FeedbackType;
  reply_text: string | null;
  created_at: string;
};

// ─── Annotation Style ───

export type AnnotationFont =
  | "default"
  | "fraunces"
  | "kalam"
  | "helvetica"
  | "arial"
  | "georgia";
export type AnnotationFontSize = "small" | "default" | "large";

// ─── Site Adapter Registry ───

export type StabilitySignal = {
  type: "selector_appears" | "selector_disappears" | "attribute_change";
  target_selector: string;
  attribute?: string;
  value?: string;
};

export type SiteAdapter = {
  id: string;
  hostname_pattern: string;
  content_selectors: string[];
  response_selector: string | null;
  stability_signal: StabilitySignal | null;
  excluded_selectors: string[];
  extraction_mode: "adapter" | "readability" | "custom_heuristic";
  enabled: boolean;
  updated_at: string;
};

// ─── User ───

export type UserTier = "free" | "standard";

export type SubscriptionStatus =
  | "active"
  | "past_due"
  | "canceled"
  | "incomplete"
  | "trialing"
  | "unpaid"
  | null;

export type BillingInterval = "month" | "quarter" | "year" | null;

export type UserProfile = {
  id: string;
  display_name: string | null;
  tier: UserTier;
  subscription_status: SubscriptionStatus;
  billing_interval: BillingInterval;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  monthly_annotation_count: number;
  preferences: UserPreferences;
  created_at: string;
};

export type UserPreferences = {
  enabled?: boolean;
  annotation_mode?: AnnotationMode;
  depth_context_mode?: UserContextMode;
  depth_context_note?: string;
  visible_types?: AnnotationType[];
  enabled_sites?: string[];
  annotation_font?: AnnotationFont;
  annotation_font_size?: AnnotationFontSize;
};

// ─── API Request/Response ───

export type AnnotateRequest = {
  url: string;
  content_hash: string;
  text: string;
  mode: AnnotationMode;
  user_context?: UserContext;
  word_count: number;
};

export type ReadingRegion = {
  id: string;
  element: string; // CSS selector or description for debugging
  text: string;
  wordCount: number;
  contentHash: string;
};

// ─── Extension Internal Messaging ───

export type ExtensionMessage =
  | {
      action: "requestAnnotations";
      payload: {
        url: string;
        regionId: string;
        contentHash: string;
        text: string;
        mode: AnnotationMode;
        userContext?: UserContext;
        wordCount: number;
      };
    }
  | {
      action: "annotationsReady";
      payload: {
        regionId: string;
        annotations: Annotation[];
        feedback: AnnotationFeedback[];
      };
    }
  | {
      action: "saveManualAnnotation";
      payload: {
        url: string;
        contentHash: string;
        annotation: Annotation;
        pageTitle?: string;
      };
    }
  | {
      action: "deleteAnnotation";
      payload: {
        annotationId: string;
        url: string;
        contentHash: string;
      };
    }
  | {
      action: "settingsUpdated";
      payload: {
        enabled: boolean;
        annotationMode: AnnotationMode;
        depthContextMode?: UserContextMode;
        depthContextNote?: string;
        visibleTypes: AnnotationType[];
        annotationFont?: AnnotationFont;
        annotationFontSize?: AnnotationFontSize;
      };
    }
  | {
      action: "getAdapters";
      payload: Record<string, never>;
    }
  | {
      action: "adaptersResponse";
      payload: {
        adapters: SiteAdapter[];
      };
    }
  | {
      action: "exportAnnotations";
      payload: {
        url: string;
      };
    }
  | {
      action: "getAuthStatus";
      payload: Record<string, never>;
    }
  | {
      action: "authStatusResponse";
      payload: {
        authenticated: boolean;
        user: { id: string; email: string } | null;
      };
    }
  | { action: "signIn"; payload: { email: string; password: string } }
  | {
      action: "signUp";
      payload: { email: string; password: string; displayName: string };
    }
  | { action: "signOut"; payload: Record<string, never> }
  | { action: "signInWithGoogle"; payload: Record<string, never> }
  | { action: "resetPassword"; payload: { email: string } }
  | { action: "deleteAccount"; payload: Record<string, never> }
  | { action: "getProfile"; payload: Record<string, never> }
  | { action: "updateProfile"; payload: { display_name: string } }
  | { action: "exportPdf"; payload: { title: string; subtitle: string } }
  | { action: "exportPdfResult"; payload: { success: boolean; error?: string } }
  | { action: "getUserTier"; payload: Record<string, never> }
  | { action: "getUserTierResult"; payload: { tier: UserTier } }
  | {
      action: "saveFeedback";
      payload: {
        annotationId: string;
        contentHash: string;
        url: string;
        feedbackType: FeedbackType;
        replyText?: string;
        pageTitle?: string;
      };
    }
  | {
      action: "updateFeedback";
      payload: { feedbackId: string; replyText: string; contentHash?: string; url?: string };
    }
  | { action: "deleteFeedback"; payload: { feedbackId: string; contentHash?: string; url?: string } }
  | {
      action: "updateAnnotation";
      payload: {
        annotationId: string;
        annotation: Annotation;
        url: string;
        contentHash: string;
        pageTitle?: string;
      };
    }
  | { action: "sendUserFeedback"; payload: { message: string; role?: string } }
  | {
      action: "annotationReady";
      payload: { regionId: string; annotation: Annotation };
    }
  | { action: "getUrlPrediction"; payload: { url: string } }
  | { action: "getEnabledSites"; payload: Record<string, never> }
  | { action: "addEnabledSite"; payload: { domain: string } }
  | { action: "removeEnabledSite"; payload: { domain: string } }
  | { action: "enabledSitesUpdated"; payload: { sites: string[] } }
  | { action: "abortAllRequests"; payload: Record<string, never> }
  | { action: "setBadge"; payload: { text: string; color?: string } }
  | { action: "openPopup"; payload: Record<string, never> }
  | { action: "openOptions"; payload: Record<string, never> }
  | {
      action: "authStateChanged";
      payload:
        | { authenticated: false }
        | {
            authenticated: true;
            user: {
              email: string;
              display_name: string | null;
              tier: string;
              annotation_count: number;
            };
          };
    }
  | {
      action: "requestSketch";
      payload: {
        inputText: string;
        purpose: string;
        userReactions: string;
      };
    }
  | {
      action: "sketchChunk";
      payload: { text: string; done: boolean };
    }
  | { action: "injectNextNewTab"; payload: Record<string, never> }
  | { action: "fetchPdfData"; payload: { url: string } };
