// ─── Annotation Types (LLM Output Contract) ───

export type AnnotationType =
  | 'highlight'
  | 'recall'
  | 'provoking_question'
  | 'insight'
  | 'caveat'
  | 'vocabulary';

export type TextQuoteSelector = {
  type: 'TextQuoteSelector';
  exact: string;
  prefix?: string;
  suffix?: string;
};

export type AnnotationContent = {
  note: string;
  why_it_matters?: string;
  question?: string;
  /** @deprecated No longer generated by LLM, kept for cached data backward compat */
  suggestions?: string[];
};

export type Annotation = {
  id: string;
  type: AnnotationType;
  anchor: TextQuoteSelector;
  content: AnnotationContent;
};

export type AnnotationResponse = {
  success: boolean;
  cached: boolean;
  annotations: Annotation[];
  feedback?: AnnotationFeedback[];
};

// ─── Feedback ───

export type FeedbackType = 'thumbs_up' | 'thumbs_down' | 'reply';

export type AnnotationFeedback = {
  id: string;
  annotation_id: string;
  feedback_type: FeedbackType;
  reply_text: string | null;
  created_at: string;
};

// ─── Intensity ───

export type Intensity = 'light' | 'default' | 'heavy';

// ─── Annotation Style ───

export type AnnotationFont = 'default' | 'kalam' | 'helvetica' | 'arial' | 'georgia';
export type AnnotationFontSize = 'small' | 'default' | 'large';

// ─── Site Adapter Registry ───

export type StabilitySignal = {
  type: 'selector_appears' | 'selector_disappears' | 'attribute_change';
  target_selector: string;
  attribute?: string;
  value?: string;
};

export type SiteAdapter = {
  id: string;
  hostname_pattern: string;
  content_selectors: string[];
  response_selector: string | null;
  stability_signal: StabilitySignal | null;
  excluded_selectors: string[];
  extraction_mode: 'adapter' | 'readability' | 'custom_heuristic';
  enabled: boolean;
  updated_at: string;
};

// ─── User ───

export type UserTier = 'free' | 'pro';

export type UserProfile = {
  id: string;
  display_name: string | null;
  tier: UserTier;
  preferences: UserPreferences;
  created_at: string;
};

export type UserPreferences = {
  enabled?: boolean;
  intensity?: Intensity;
  visible_types?: AnnotationType[];
  disabled_sites?: string[];
  annotation_font?: AnnotationFont;
  annotation_font_size?: AnnotationFontSize;
};

// ─── API Request/Response ───

export type AnnotateRequest = {
  url: string;
  content_hash: string;
  text: string;
  intensity: Intensity;
  word_count: number;
};

export type ReadingRegion = {
  id: string;
  element: string; // CSS selector or description for debugging
  text: string;
  wordCount: number;
  contentHash: string;
};

// ─── Extension Internal Messaging ───

export type ExtensionMessage =
  | {
      action: 'requestAnnotations';
      payload: {
        url: string;
        regionId: string;
        contentHash: string;
        text: string;
        intensity: Intensity;
        wordCount: number;
      };
    }
  | {
      action: 'annotationsReady';
      payload: {
        regionId: string;
        annotations: Annotation[];
        feedback: AnnotationFeedback[];
      };
    }
  | {
      action: 'saveManualAnnotation';
      payload: {
        url: string;
        contentHash: string;
        annotation: Annotation;
      };
    }
  | {
      action: 'deleteAnnotation';
      payload: {
        annotationId: string;
        url: string;
        contentHash: string;
      };
    }
  | {
      action: 'settingsUpdated';
      payload: {
        enabled: boolean;
        intensity: Intensity;
        visibleTypes: AnnotationType[];
        annotationFont?: AnnotationFont;
        annotationFontSize?: AnnotationFontSize;
      };
    }
  | {
      action: 'getAdapters';
      payload: Record<string, never>;
    }
  | {
      action: 'adaptersResponse';
      payload: {
        adapters: SiteAdapter[];
      };
    }
  | {
      action: 'exportAnnotations';
      payload: {
        url: string;
      };
    }
  | {
      action: 'getAuthStatus';
      payload: Record<string, never>;
    }
  | {
      action: 'authStatusResponse';
      payload: {
        authenticated: boolean;
        user: { id: string; email: string } | null;
      };
    }
  | { action: 'signIn'; payload: { email: string; password: string } }
  | { action: 'signUp'; payload: { email: string; password: string; displayName: string } }
  | { action: 'signOut'; payload: Record<string, never> }
  | { action: 'getProfile'; payload: Record<string, never> }
  | { action: 'updateProfile'; payload: { display_name: string } }
  | { action: 'exportPdf'; payload: { title: string; subtitle: string } }
  | { action: 'exportPdfResult'; payload: { success: boolean; error?: string } }
  | { action: 'getUserTier'; payload: Record<string, never> }
  | { action: 'getUserTierResult'; payload: { tier: UserTier } }
  | { action: 'saveFeedback'; payload: { annotationId: string; contentHash: string; url: string; feedbackType: FeedbackType; replyText?: string } }
  | { action: 'deleteFeedback'; payload: { feedbackId: string } }
  | { action: 'updateAnnotation'; payload: { annotationId: string; annotation: Annotation; url: string; contentHash: string } }
  | { action: 'sendUserFeedback'; payload: { message: string } }
  | { action: 'annotationReady'; payload: { regionId: string; annotation: Annotation } }
  | { action: 'getUrlPrediction'; payload: { url: string } };
